mod point;
mod racer;

use crate::point::Point;
use crate::racer::Racer;

use include_f64_matrix::*;
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = console)]
    fn log(s: &str);
}

macro_rules! console_log {
    ($($t:tt)*) => (log(&format_args!($($t)*).to_string()))
}

#[wasm_bindgen]
pub fn greet(name: &str) -> String {
    console_log!("Hello from Rust! Greeting: {}", name);
    format!(
        "Hello, {}! This message was generated by Rust and deez.",
        name
    )
}

#[wasm_bindgen]
pub fn step(racers: Vec<Racer>, track: Vec<Point>) -> Vec<Racer> {
    const DELTA: f64 = 0.1; // TODO replace DELTA occurrences with Racer.speed or similar
    fn curve_function(_track: &[Point], t: f64) -> Point {
        let track_points = wrapping_control_points(_track.to_vec());
        track_points[(t * track_points.len() as f64) as usize]
    }
    fn normal_function(_track: &[Point], t: f64) -> Point {
        let track_points = wrapping_control_points(_track.to_vec());
        let t = (t * track_points.len() as f64) as usize;
        let behind = track_points[(t - 1) % track_points.len()];
        let ahead = track_points[(t + 1) % track_points.len()];
        let midpoint = Point {
            x: (behind.x + ahead.x) / 2.0,
            y: (behind.y + ahead.y) / 2.0,
        };
        Point {
            x: midpoint.x + (behind.y - midpoint.y),
            y: midpoint.y - (behind.x - midpoint.x),
        } - midpoint
    }
    fn update_racer(track: &[Point], r: Racer) -> Racer {
        fn update_t(track: &[Point], r: Racer) -> Racer {
            let track_position: Point = curve_function(track, r.t);
            let offset_position: Point = normal_function(track, r.t) * r.offset + track_position;
            let target: Point = curve_function(track, r.t + DELTA);
            let offset_bonus = target.distance(&offset_position) - target.distance(&track_position);
            if offset_bonus < 0. {
                console_log!("Inner corner!");
            }
            Racer {
                t: r.t + DELTA + offset_bonus / 2.0,
                ..r
            }
        }
        let update_t = |r| update_t(track, r);
        update_t(r)
    }
    racers
        .into_iter()
        .map(|r| update_racer(&track, r))
        .collect()
}

#[allow(clippy::excessive_precision)]
#[wasm_bindgen]
pub fn wrapping_control_points(points: Vec<Point>) -> Vec<Point> {
    const OVERLAP_OFFSET: u64 = 3;
    const INDEX_OFFSET: u64 = 1;
    const N: u32 = 3;
    const INPUT_LEN: u64 = 2u64.pow(N) + OVERLAP_OFFSET - INDEX_OFFSET;
    static MATRIX: [[f64; 11]; 2500] = include_f64_matrix!("precomputed-matrix.txt");

    MATRIX.iter().fold(vec![], |mut acc, t| {
        acc.push(Point {
            x: t.iter()
                .zip(points.iter().map(|x| x.x))
                .fold(0 as f64, |acc, (t, x)| acc + t * x),
            y: t.iter()
                .zip(points.iter().map(|x| x.y))
                .fold(0 as f64, |acc, (t, y)| acc + t * y),
        });
        acc
    })
}

#[wasm_bindgen(start, private)]
pub fn main() {
    console_log!("working on getting points, and therefore arbitrary structs, to make sense");
}

#[cfg(test)]
mod tests;
