CREATE TABLE users
(
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	username VARCHAR(20) NOT NULL UNIQUE,
	email TEXT NOT NULL UNIQUE,
	passwordHash TEXT NOT NULL,
	firstName VARCHAR(20) NOT NULL,
	lastName VARCHAR(20) NOT NULL,
	country TEXT,
	city TEXT,
	birthday DATE NOT NULL,
	avatar TEXT,
	twoFactorEnabled BOOLEAN NOT NULL DEFAULT FALSE,
	twoFactorSecret TEXT,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastLogin TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	isActive BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE statistics
(
	userId INTEGER PRIMARY KEY,
	matchesPlayed INTEGER NOT NULL DEFAULT 0,
	wins INTEGER NOT NULL DEFAULT 0,
	losses INTEGER NOT NULL DEFAULT 0,

	totalPitStops INTEGER NOT NULL DEFAULT 0,
	perfectPitStops INTEGER NOT NULL DEFAULT 0,
	fastestPitStopTime INTEGER NOT NULL DEFAULT 0,

	totalCrashes INTEGER NOT NULL DEFAULT 0,

	FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE --Delete statistics if user gets deleted.
);

CREATE TABLE matches
(
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	winningTeam INTEGER NOT NULL,
	startedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	finishedAt TIMESTAMP,
	gameMode ENUM NOT NULL
);

CREATE TABLE matchPlayers
(
	userId INTEGER NOT NULL,
	matchId INTEGER NOT NULL,
	team INTEGER NOT NULL,

	FOREIGN KEY (userId) REFERENCES users(id),
	FOREIGN KEY (matchId) REFERENCES matches(id),
	PRIMARY KEY(matchId, userId)
);

CREATE TABLE friendships
(
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

	requesterId INTEGER NOT NULL,
	receiverId INTEGER NOT NULL,

	status TEXT NOT NULL DEFAULT 'PENDING',

	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (requesterId) REFERENCES users(id),
	FOREIGN KEY (receiverId) REFERENCES users(id)
);

CREATE TABLE achievements
(
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL,
	description TEXT NOT NULL
);

CREATE TABLE userAchievements
(
	userId INTEGER NOT NULL,
	achievementId INTEGER NOT NULL,
	unlockedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (userId) REFERENCES users(id),
	FOREIGN KEY (achievementId) REFERENCES achievements(id),
	PRIMARY KEY(achievementId, userId)
);