use std::ops::{Add, Mul};

use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = console)]
    fn log(s: &str);
}

macro_rules! console_log {
    ($($t:tt)*) => (log(&format_args!($($t)*).to_string()))
}

#[wasm_bindgen]
pub fn greet(name: &str) -> String {
    console_log!("Hello from Rust! Greeting: {}", name);
    format!(
        "Hello, {}! This message was generated by Rust and deez.",
        name
    )
}

#[wasm_bindgen]
pub fn fibonacci(n: u32) -> u32 {
    match n {
        0 => 0,
        1 => 1,
        _ => fibonacci(n - 1) + fibonacci(n - 2),
    }
}

#[wasm_bindgen]
pub fn process_numbers(numbers: &[f64]) -> Vec<f64> {
    numbers.iter().map(|x| x * x + 1.0).collect()
}

#[wasm_bindgen]
#[derive(Clone, Copy)]
pub struct Point {
    pub x: f64,
    pub y: f64,
}

#[wasm_bindgen]
impl Point {
    #[wasm_bindgen(constructor)]
    pub fn new(x: f64, y: f64) -> Point {
        Point { x, y }
    }

    #[wasm_bindgen(js_name = clone)]
    pub fn dup(&self) -> Point {
        *self
    }
    pub fn distance(&self, other: &Point) -> f64 {
        ((self.x - other.x).powi(2) + (self.y - other.y).powi(2)).sqrt()
    }
    pub fn add(&self, other: &Point) -> Point {
        Point {
            x: self.x + other.x,
            y: self.y + other.y,
        }
    }
}
impl Add for Point {
    type Output = Self;

    fn add(self, other: Self) -> Self {
        Self {
            x: self.x + other.x,
            y: self.y + other.y,
        }
    }
}
impl Add<&Point> for Point {
    type Output = Self;

    fn add(self, other: &Self) -> Self {
        Self {
            x: self.x + other.x,
            y: self.y + other.y,
        }
    }
}
impl Add<f64> for Point {
    type Output = Self;
    fn add(self, other: f64) -> Self {
        Self {
            x: self.x + other,
            y: self.y + other,
        }
    }
}
impl Mul<f64> for Point {
    type Output = Self;
    fn mul(self, other: f64) -> Self {
        Self {
            x: self.x * other,
            y: self.y * other,
        }
    }
}
impl std::fmt::Display for Point {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "(x: {}, y: {})", self.x, self.y)
    }
}

#[wasm_bindgen]
pub struct Racer {
    pub t: f64,
    pub offset: f64,
}
#[wasm_bindgen]
impl Racer {
    #[wasm_bindgen(constructor)]
    pub fn new(t: f64, offset: f64) -> Racer {
        Racer { t, offset }
    }
}

impl Default for Racer {
    fn default() -> Self {
        Self::new(0., 0.)
    }
}

#[wasm_bindgen]
pub fn step(racers: Vec<Racer>, track: Vec<Point>) -> Vec<Racer> {
    const DELTA: f64 = 0.1; // TODO replace DELTA occurrences with Racer.speed or similar
    fn curve_function(_track: &[Point], t: f64) -> Point {
        Point {
            x: -t.sin(),
            y: -t.cos(),
        }
    }
    fn normal_function(_track: &[Point], t: f64) -> Point {
        Point {
            x: -t.sin(),
            y: -t.cos(),
        }
    }
    fn update_racer(track: &[Point], r: Racer) -> Racer {
        fn update_t(track: &[Point], r: Racer) -> Racer {
            let track_position: Point = curve_function(track, r.t);
            let offset_position: Point = normal_function(track, r.t) * r.offset + track_position;
            let target: Point = curve_function(track, r.t + DELTA);
            let offset_bonus = target.distance(&offset_position) - target.distance(&track_position);
            if offset_bonus < 0. {
                console_log!("Inner corner!");
            }
            Racer {
                t: r.t + DELTA + offset_bonus / 2.0,
                ..r
            }
        }
        let update_t = |r| update_t(track, r);
        update_t(r)
    }
    racers
        .into_iter()
        .map(|r| update_racer(&track, r))
        .collect()
}

#[wasm_bindgen]
pub fn wrapping_control_points(points: Vec<Point>) -> Vec<Point> {
    const OVERLAP_OFFSET: u64 = 3;
    const INDEX_OFFSET: u64 = 1;
    const N: u32 = 3;
    const INPUT_LEN: u64 = 2u64.pow(N) + OVERLAP_OFFSET - INDEX_OFFSET;
    const MATRIX_STR: &str = include_str!("../precomputed-matrix.txt");

    let matrix: Vec<Vec<f64>> = include_str!("../precomputed-matrix.txt")
        .lines()
        .map(|l| l.split(' ').map(|f| f.parse::<f64>().unwrap()).collect())
        .collect();
    matrix.iter().fold(vec![], |mut acc, t| {
        acc.push(Point {
            x: t.iter()
                .zip(points.iter().map(|x| x.x))
                .fold(0 as f64, |acc, (t, x)| acc + t * x),
            y: t.iter()
                .zip(points.iter().map(|x| x.y))
                .fold(0 as f64, |acc, (t, y)| acc + t * y),
        });
        acc
    })
}

#[wasm_bindgen(start, private)]
pub fn main() {
    console_log!("working on getting points, and therefore arbitrary structs, to make sense");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_wrapping_control_points() -> Result<(), String> {
        const EPSILON: f64 = 0.0001;
        const REFERENCE_STR: &str = include_str!("../points.py");
        const POINTS: [Point; 11] = [
            Point { x: 1.0, y: 2.0 },
            Point { x: 2.0, y: 3.0 },
            Point { x: 3.5, y: 2.0 },
            Point { x: 3.0, y: 10.0 },
            Point { x: 4.0, y: 10.0 },
            Point { x: 3.5, y: 2.0 },
            Point { x: 6.0, y: -12.0 },
            Point { x: 4.0, y: -5.0 },
            Point { x: 1.0, y: 2.0 },
            Point { x: 2.0, y: 3.0 },
            Point { x: 3.0, y: 2.0 },
        ];

        let reference: Vec<Point> = REFERENCE_STR
            .lines()
            .map(|l| l.split(',').map(|f| f.parse().unwrap()).collect())
            .map(|v: Vec<f64>| Point { x: v[0], y: v[1] })
            .collect();
        let actual: Vec<Point> = wrapping_control_points(POINTS.into());
        if reference.len() != actual.len() {
            return Err(format!(
                "different amount of points between reference and actual result ({}, {})",
                reference.len(),
                actual.len()
            ));
        } else {
            for i in 0..reference.len() {
                if reference[i].distance(&actual[i]) > EPSILON {
                    return Err(format!(
                        "difference between points on line {} is larger than {}: {} ({}, {})",
                        i,
                        EPSILON,
                        reference[i].distance(&actual[i]),
                        reference[i],
                        actual[i]
                    ));
                }
            }
        }
        Ok(())
    }
}
